SPRINT02_US06_HOME_PAGE_SECTION_2 Affichage section "Offres Spéciales"
WildCodeSchool/orleans-0918-php-ohterroir pull request #18
Opened 2018-10-18 09:55 UTC by accuratecopy

2018-10-19 08:02 UTC, open-it requested changes

2018-10-19 08:02 UTC, open-it commented on src/Model/SpecialOffers.php
> +    /** @var string */
ca serait plutot un DateTime pour le type (avec ou sans \ je vous laisse réfléchir)

2018-10-19 08:02 UTC, open-it commented on src/Model/SpecialOffers.php
> +    /** @var string */
pareil

2018-10-19 08:02 UTC, open-it commented on src/Model/SpecialOffers.php
> +    /** @var int */
Ca ne serait pas plutot un boolean ? ou alors j'ai pas compris à quoi cela servait ?

2018-10-19 08:02 UTC, open-it commented on src/Model/SpecialOffersManager.php
> +            'SELECT * FROM ' . $this->table .
Je pense que votre requete n'est pas correcte. Mais à vérifier.

2018-10-19 08:02 UTC, open-it commented on src/Model/SpecialOffersManager.php
> +            'SELECT * FROM ' . $this->table .
Comme je n'ai pas de commentaire sur ce qu'est sensé faire cette méthode je ne peux pas en etre sur.

2018-10-24 12:17 UTC, open-it requested changes

2018-10-24 12:17 UTC, open-it commented on src/View/specialOffers.html.twig
> +                        <p>Période du : {{ specialoffer.startdate|date('d-m-Y') }} au {{ specialoffer.finishdate|date('d-m-Y') }}</p>
les dates en FR sont au format d/m/Y

2018-10-24 12:17 UTC, open-it commented on src/Model/SpecialOffers.php
> +    /** @var int */
plus bas il y a un bool sur les getter / setter ?

2018-10-24 12:17 UTC, open-it commented on src/Model/SpecialOffersManager.php
> +            'SELECT * FROM ' . $this->table .
je ne comprend tjrs pas cette requete si quelqu'un pouvait passer.

2018-10-24 12:39 UTC, open-it requested changes

2018-10-24 12:39 UTC, open-it commented on src/Model/SpecialOffersManager.php
> +    public function show() : array
A renommer

2018-10-24 12:39 UTC, open-it commented on src/Model/SpecialOffers.php
> +    /** @var int */
finalement cette propriété disparait.

2018-10-25 14:49 UTC, sblondeau requested changes

2018-10-25 14:49 UTC, sblondeau commented on data/oh_terroir_2018_specialOffer.sql
> +CREATE DATABASE  IF NOT EXISTS `oh_terroir_2018` /*!40100 DEFAULT CHARACTER SET utf8 */;
pas de dump sql versionnés

2018-10-25 14:49 UTC, sblondeau commented on src/Model/SpecialOfferManager.php
> +            ' WHERE ((specialOffer.startDate <= NOW()
c'est pas le contraire que tu veux faire (startdate>NOW et enddate<NOW ?) et dans ce cas un BETWEEN serait plus adapté je pense

2018-10-25 14:49 UTC, sblondeau commented on src/Model/SpecialOfferManager.php
> +            $specialOffer = new SpecialOffer();
euh... ta requete ne porte QUE sur la table SpecialOffer, donc tu peux faire un FETCH_CLASS et du coup tu récupère direct un tableau d'objets SpecialOffer (ce que tu récréé à la main ici sinon, c'est complqiué et inutile du coup)

2018-10-26 08:24 UTC, open-it approved these changes

2018-10-26 08:24 UTC, open-it commented on data/oh_terroir_2018_specialOffer.sql
> +CREATE DATABASE  IF NOT EXISTS `oh_terroir_2018` /*!40100 DEFAULT CHARACTER SET utf8 */;
Si on les versionne pour éviter les copier / coller dégueu via le tchat. Quand tu versionnes tes entités doctrine en Symfony avec tous leurs mappings tu donnes accès aux même infos.

2018-10-26 12:36 UTC, merged