Sprint02 us07 home page section03 avis tripAdvisor
WildCodeSchool/orleans-0918-php-ohterroir pull request #24
Opened 2018-10-19 13:01 UTC by Luluribe45

2018-10-23 17:27 UTC, open-it requested changes

2018-10-23 17:27 UTC, open-it commented on public/assets/css/styles.css
> +    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%7fb401' viewBox='0 0 8 8'%3E%3Cpath d='M5.25 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%
qu est ce que c est que cette image  ?

2018-10-23 17:27 UTC, open-it commented on src/Controller/HomeController.php
> +        $opinionTripAdvisor = $opinionTripAdvisorManager->selectAllOpinionsTripAdvisor();
Récupères tu un seul avis ? (nommage de ta variable)

2018-10-23 17:27 UTC, open-it commented on src/Model/OpinionTripAdvisor.php
> +    private $date;
une date doit être du type DateTime

2018-10-23 17:27 UTC, open-it commented on src/Model/OpinionTripAdvisorManager.php
> +    public function selectAllOpinionsTripAdvisor(): array
si tu fais un selectAll cette méthode est inutile

2018-10-24 06:54 UTC, Luluribe45 commented on public/assets/css/styles.css
> +    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%7fb401' viewBox='0 0 8 8'%3E%3Cpath d='M5.25 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%
c'est pour changer la couleur des fleches pour navigué sur les avis.

2018-10-24 12:58 UTC, open-it requested changes

2018-10-24 12:58 UTC, open-it commented on src/View/Home/tripAdvisor.html.twig
> +                    <p>Evalué par {{ opinion.pseudo }} à {{ opinion.note }}/5. Le {{ opinion.DateOpinion|date('d-m-Y') }}.</p>
les dates au format FR sont comme cela d/m/Y

2018-10-24 14:50 UTC, open-it requested changes

2018-10-24 14:50 UTC, open-it commented on src/Controller/HomeController.php
> +            "opinionTripAdvisor" => $opinionsTripAdvisor,
tu as mis le s d'un coté et pas de l'autres.... pourtant il y en a toujours plusieurs des opinions.

2018-10-24 14:50 UTC, open-it commented on src/Model/OpinionTripAdvisor.php
> +class OpinionTripAdvisor extends \DateTime
pourquoi on étend de DateTime ?

2018-10-24 14:50 UTC, open-it commented on src/Model/OpinionTripAdvisor.php
> +        return $date = new \DateTime($this->date, $timeZone);
faux ! ici tu retournes un boolean.
pourquoi le getter s'appelle getDateOpinion alors qu'il n'existe pas de propriété dateOpinion

2018-10-24 14:50 UTC, open-it commented on src/Model/OpinionTripAdvisor.php
> +        $this->date = $date;
Le setter s'appelle setDateOpinion il doit manipuler la propriété dateOpinion or cette propriété n'existe pas...

2018-10-25 14:52 UTC, sblondeau requested changes

2018-10-25 14:52 UTC, sblondeau commented on data/oh_terroir_2018_dishCategory.sql
> +-- MySQL dump 10.13  Distrib 5.7.23, for Linux (x86_64)
pas de dump sql

2018-10-25 14:52 UTC, sblondeau commented on src/View/Home/tripAdvisor.html.twig
> +            <div class="carousel-item {{ active }} text-center p-4 ">
tu veux que le 1er item de ton carousel soit actif par défaut ? je crois que tu n'a pas besoin de l'indiquer dans ce cas. Ou sinon, utilises plutot loop.first qui permet de voir si tu es ou non au premier tour de boucle

2018-10-29 08:42 UTC, open-it approved these changes

2018-10-29 08:43 UTC, merged