SPRINT03_US30_PRESENTATION_PAGE_PRODUCTEURS_SECTION_1
WildCodeSchool/orleans-0918-php-ohterroir pull request #27
Opened 2018-10-24 13:58 UTC by Luluribe45

2018-10-25 15:29 UTC, sblondeau commented
PR sur MASTER => GATEAU !!!

2018-10-26 08:08 UTC, open-it requested changes

2018-10-26 08:08 UTC, open-it commented on src/Controller/GrowerController.php
> +    public function show()
stp renomme ta method en index et ta vue également. J'ai deja fait la remarque. Pour les vues, le dossier est le nom du controller et le fichier le nom de la methode. L'index étant la liste et le show, l'affichage d'une entité.

2018-10-26 08:08 UTC, open-it commented on src/Controller/GrowerController.php
> +            "growerPage" => "active",
Quelle est cette variable growerPage qui contient un active ?? Je ne comprend pas son nommage ou à quoi elle sert ?

2018-10-26 09:49 UTC, open-it approved these changes

2018-10-26 09:49 UTC, merged