Sprint01 us02 diaporama
WildCodeSchool/orleans-0918-php-ohterroir pull request #3
Opened 2018-10-12 14:37 UTC by LN45

Sprint01 us02 diaporama fait

2018-10-12 14:51 UTC, sblondeau requested changes

2018-10-12 14:51 UTC, sblondeau commented on public/assets/css/styles.css
> +
je ne devrais pas avoir toutes ces lignes vides

2018-10-12 14:51 UTC, sblondeau commented on public/assets/css/styles.css
> +@media screen and (max-width: 64em) {
pourquoi autant de mediaqueries ? tu ne devrais pas en avoir besoin ? c'était dans le template de base ou c'est toi qui les a ajouté?

2018-10-12 15:13 UTC, LN45 commented on public/assets/css/styles.css
> +@media screen and (max-width: 64em) {
Dans le thème principal, le h1 était dans le carousel géré en javascript. on a voulu ressortir le h1 et j'ai effectivement rajouté les mediaqueries pour l'adaptation tablette/mobile

2018-10-12 15:14 UTC, LN45 commented on public/assets/css/styles.css
> +
effectivement, je m'étais ajusté sur la branche précédente mais ce n'était pas utile. je vais les enlever

2018-10-13 18:24 UTC, sblondeau approved these changes

2018-10-15 09:17 UTC, merged