SPRINT03 US44 AFFICHAGE COORDONNEES_ Admin
WildCodeSchool/orleans-0918-php-ohterroir pull request #30
Opened 2018-10-25 12:58 UTC by Amandine1345

2018-10-25 15:33 UTC, sblondeau requested changes

2018-10-25 15:33 UTC, sblondeau commented on src/Controller/ContactDetailsController.php
> +        $contactDetails = $contactManager->selectAll();
si je comprends bien, tu n'as qu'un seul enregistrement dans cette table ? 
donc tu devrais faire une requete personnalisée qui te fais un fetch et non un fetchAll, tu auras ainsi qu'un seul enregistrement (objet Contact et non plus un tableau d'objets Contact)
Et du coup, plus besoin de boucler dans ton twig pour récup uniquement l'index 0, pas très optimisé.

2018-10-25 19:09 UTC, Amandine1345 commented on src/Controller/ContactDetailsController.php
> +        $contactDetails = $contactManager->selectAll();
Ok, méthode selectUniqueEntry() créée dans le manager.

2018-10-29 13:07 UTC, open-it approved these changes

2018-10-29 13:07 UTC, merged